"""Add profile model

Revision ID: d929caca1fba
Revises: 
Create Date: 2025-08-20 18:01:57.332601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd929caca1fba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('offered_skills', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('required_skills', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'required_skills')
    op.drop_column('profiles', 'offered_skills')
    # ### end Alembic commands ###
